version: '3.5'

services:

  rmq-balancer:
    image: rmq:deduplication
    container_name: rmq-balancer
    hostname: rmq-balancer
    volumes:
      - ./:/var/lib/rabbitmq/mnesia/
    ports:
      - 8181:15672
      - 5672:5672
    networks:
      - d3-network

networks:
  d3-network: